---
title: "Chapter 3 Exercises"
author: "Drew Insley"
date: "1/20/19"
output: html_notebook
---

# Front Matter

```{r message=FALSE, warning=FALSE}
# clean the enviornment
rm(list = ls())

# load packages
library(NHANES)
library(ggplot2)
library(mosaic)
library(babynames)
library(mdsr)
library(Hmisc)


#load data
data("NHANES")
BabynamesDist <- make_babynames_dist()
```

## Reproduce Figure 3.18

```{r}
# p. 47

# Inspect the Data
NHANES

# Data Wrangling
NHANES2 <-
  NHANES %>%
  select(AgeDecade, BMI_WHO, Diabetes) %>%
  arrange(AgeDecade)

NHANES2Clean <-
  NHANES2[- c(1:2766), ]

NHANES2Plot <-
  mosaicplot(~ droplevels(AgeDecade) + BMI_WHO + Diabetes, data = NHANES2Clean, shade = TRUE, xlab = "AgeDecade")

```

## Reproduce Figure 3.27

```{r}
# p. 56
com_fem <-
  BabynamesDist %>%
  filter(sex == "F",
         est_alive_today > 0) %>%
  group_by(name) %>%
  summarise(N = n(),
            est_num_alive = sum(est_alive_today),
            q1_age = wtd.quantile(age_today, est_alive_today, probs = .25) ,
            median_age = wtd.quantile(age_today, est_alive_today, probs = .5),
            q3_age = wtd.quantile(age_today, est_alive_today, probs = .75)) %>%
  arrange(desc(est_num_alive)) %>%
  head(25)

com_fem
```

```{r}
# p. 56 - 58
w_plot <-
  com_fem %>%
  ggplot(aes(x = reorder(name, -median_age), y = median_age)) +
  xlab(NULL) +
  ylab("Age (in years)") +
  ggtitle("Median ages for females with the 25 most common names")

w_plot <-
  w_plot +
  geom_linerange(aes(ymin = q1_age, ymax = q3_age), color = "#f3d478", size = 10, alpha = 0.8)

w_plot <-
  w_plot +
  geom_point(fill = "#ed3324", colour = "white", size = 4, shape = 21)

w_plot +
  geom_point(aes(y = 55, x = 24), fill = "#ed3324", colour = "white", size = 4, shape = 21) +
  geom_text(aes(y = 58, x = 24, label = "median")) +
  geom_text(aes(y = 26, x = 16, label = "25th")) +
  geom_text(aes(y = 51, x = 16, label = "75th percentile")) +
  geom_point(aes(y = 24, x = 16), shape = 17) +
  geom_point(aes(y = 56, x =16), shape = 17) +
  coord_flip()
```



